Algoritmo "Incremento"
// Descrição   : Incrementação
// Autor(a)    : Pedro Jr. F. Santos
// Data inicial  : 02/02/2024

Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Entrada de dados
   Escreva ("Digite um número inteiro: ")
   leia (numero)

   //Incremento do número
   numero <- numero + 1

   //Exibição do resultado
   escreva ("O número incrementado é:", numero)

Fimalgoritmo